objectTypes:
  Persoon:
    attributes:
      bsn:
        type: String
        identifier: true
        multiplicity: 1
      isIngezetene:
        type: Boolean
        multiplicity: 1
      leeftijd:
        type: Integer
        multiplicity: 1
      vermogen:
        type: Integer
        multiplicity: 1
      inkomenMaandelijks:
        type: Integer
        multiplicity: 1
      inkomenJaarlijks:
        type: Integer
        multiplicity: 1

  BeschikkingZorgtoeslag:
    attributes:
      bsn:
        type: String
        identifier: true
        multiplicity: 0..1
      gerechtigd:
        type: Boolean
        multiplicity: 0..1
      bedrag:
        type: Integer
        multiplicity: 0..1
      toelichting:
        type: String
        multiplicity: 0..1
